/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.implementations.jooq;

import edu.java.domain.implementations.jooq.tables.Chat;
import edu.java.domain.implementations.jooq.tables.ChatLink;
import edu.java.domain.implementations.jooq.tables.Link;
import edu.java.domain.implementations.jooq.tables.records.ChatLinkRecord;
import edu.java.domain.implementations.jooq.tables.records.ChatRecord;
import edu.java.domain.implementations.jooq.tables.records.LinkRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[] {Chat.CHAT.CHAT_ID}, true);
    public static final UniqueKey<ChatRecord> CONSTRAINT_1F =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1F"), new TableField[] {Chat.CHAT.CHAT_ID}, true);
    public static final UniqueKey<ChatLinkRecord> CHAT_LINK_PKEY = Internal.createUniqueKey(ChatLink.CHAT_LINK,
        DSL.name("CHAT_LINK_PKEY"),
        new TableField[] {ChatLink.CHAT_LINK.CHAT_ID, ChatLink.CHAT_LINK.LINK_ID},
        true
    );
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] {Link.LINK.LINK_ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] {Link.LINK.URL}, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatLinkRecord, ChatRecord> CONSTRAINT_8 =
        Internal.createForeignKey(ChatLink.CHAT_LINK,
            DSL.name("CONSTRAINT_8"),
            new TableField[] {ChatLink.CHAT_LINK.CHAT_ID},
            Keys.CONSTRAINT_1,
            new TableField[] {Chat.CHAT.CHAT_ID},
            true
        );
    public static final ForeignKey<ChatLinkRecord, LinkRecord> CONSTRAINT_86 =
        Internal.createForeignKey(ChatLink.CHAT_LINK,
            DSL.name("CONSTRAINT_86"),
            new TableField[] {ChatLink.CHAT_LINK.LINK_ID},
            Keys.CONSTRAINT_2,
            new TableField[] {Link.LINK.LINK_ID},
            true
        );
}
