app:
  base-url-bot: "https://localhost:8080"
  base-url:
    git-hub-base-url: "https://api.github.com"
    stack-overflow-base-url: "https://api.stackexchange.com/2.3"
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: scrapper



server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

