app:
  telegram-token: 6278402620:AAHqZgjAbOMGFZl8tY6jW66gPoWz_Uy0Ukw

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
scrapper-client:
  base-url: "https://localhost:8090"
server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
